- name: Copy Filebeat repo file
  ansible.builtin.template:
    src: elk.repo
    dest: /etc/yum.repos.d/elk.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy Filebeat Configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes





