#- name: Install Maven
#  ansible.builtin.yum:
#    name: maven
#    state: installed

- name: Install Java
  ansible.builtin.yum:
    name: java-17-openjdk
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

#- name: Download Maven Dependencies
#  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#    chdir: /app

- name: Check DB exists already
  ansible.builtin.shell: echo 'show databases' | mysql -h {{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_password', region='us-east-1') }} | grep {{DBNAME}}
  ignore_errors: yes
  register: schema_check

- name: Schema Setup
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined and schema_check.rc != 0

- name: SystemD Setup
  ansible.builtin.import_tasks: systemd-setup.yml



#  echo -e "\e[36m>>>>>>>>>>>>  Install Maven   <<<<<<<<<<<<\e[0m"
#  yum install maven -y &>>${log}
#  func_exit_status
#
#  func_apppreq
#
#  echo -e "\e[36m>>>>>>>>>>>>  Build ${component} Service   <<<<<<<<<<<<\e[0m"
#  mvn clean package &>>${log}
#  mv target/${component}-1.0.jar ${component}.jar &>>${log}
#  func_exit_status
#
#  func_schema_setup
#
#  func_systemd