- name: Copy MongoDB Yum repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Download DocumentDB Pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: Load Schema
  ansible.builtin.shell:  mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'docdb.{{env}}.endpoint', region='us-east-1') }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js

