- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Check DB exists already
  ansible.builtin.shell: echo 'show databases' | mysql -h {{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_password', region='us-east-1') }} | grep {{DBNAME}}
  ignore_errors: yes
  register: schema_check

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{component}}.{{env}}.DB_HOST', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_username', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', 'rds.{{env}}.master_password', region='us-east-1') }} < /app/schema/{{component}}.sql
  when: schema_check.rc != 0

