- name: Setup SystemD service file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

## Rsyslog config
- name: Setup Rsyslog config file file
  ansible.builtin.template:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart rsyslog Service
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted


